apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namePrefix: prod-
commonLabels:
  variant: prod
  org: myOrg
commonAnnotations:
  note: Hello, I am production!
resources:
- ../../base
