kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namePrefix: staging-
commonLabels:
  org: myOrg
  variant: staging
commonAnnotations:
  note: Hello, I am staging!
bases:
- ../../base
images:
- name: dotnet-webapi
  newName: dotnet-webapi
  newTag: 1.0.staging
