namePrefix: staging-
commonLabels:
  org: myOrg
  variant: staging
commonAnnotations:
  note: Hello, I am staging!
resources:
- ../../base
images:
- name: dotnet-webapi
  newName: dotnet-webapi
  newTag: 1.0.staging
