apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dotnet-webapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dotnet-webapi
  template:
    metadata:
      labels:
        app: dotnet-webapi
    spec:
      containers:
      - image: slinehantribalscale/dotnet-argocd-poc
        name: dotnet-webapi
        ports:
        - containerPort: 80
